- name: Install python encryption module
  package:
    name: 
      - python3-cryptography
      # - security/py-cryptography

- name: Create dir for private key
  file:
    path: "{{ openssl_remote_private_dir }}"
    state: directory

- name: Generate private key
  openssl_privatekey:
    path: "{{ openssl_remote_private_key_path }}"

- name: Generate CSR
  openssl_csr:
    path: "{{ openssl_remote_for_ca_csr_path }}"
    privatekey_path: "{{ openssl_remote_private_key_path }}"
    country_name: TW
    state_or_province_name: Taiwan
    organization_name: nasa
    organizational_unit_name: "1"
    common_name: "{{ ansible_facts['fqdn'] }}"
    subject_alt_name: "DNS:{{ ansible_fqdn }}"
    email_address: "cwang.cs10@nycu.edu.tw"

- name: Pull CSR
  fetch:
    src: "{{ openssl_remote_for_ca_csr_path }}"
    dest: "{{ openssl_download_for_sign_csr_path }}"
    flat: true

- name: Sign CSR with CA key
  become: false
  connection: local
  delegate_to: localhost
  openssl_certificate:
    path: "{{ openssl_signed_csr_crt_path }}"
    csr_path: "{{ openssl_download_for_sign_csr_path }}"
    ownca_path: "{{ openssl_ownca_cert_path }}"
    ownca_privatekey_path: "{{ openssl_ownca_privatekey_path }}"
    ownca_privatekey_passphrase: "{{ openssl_ownca_privatekey_phrase }}"
    provider: ownca

- name: Push certificate
  copy:
    src: "{{ openssl_signed_csr_crt_path }}"
    dest: "{{ openssl_remote_private_cert_path }}"

# - name: Create dir for root ca
#   file:
#     path: "{{ openssl_remote_ca_cert_dir }}"
#     # path: /etc/ssl/ca-trust/source/anchors
#     state: directory

# - name: Push CA
#   copy:
#     src: "{{ openssl_ownca_cert_path }}"
#     dest: "{{ openssl_remote_ca_cert_path }}"

# - name: Rehash cert # 通過 hash 以讓應用程式能找到這個 cert
#   command: "openssl rehash {{ openssl_remote_ca_cert_dir }}"

# - name: Set ACL for LDAP user
#   command: "setfacl -Rm 'u:ldap:r-x' {{ openssl_remote_base_dir }}"