# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-stream-8"

  config.vm.provision :hosts do |provisioner|
		provisioner.autoconfigure = true
		provisioner.sync_hosts = true
	end

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = "1024"
    v.cpus   = "2"
    v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
  end
  
#   config.vm.provision "ansible" do |ansible|
#     ansible.playbook       = "../ldap-playbook.yml"
#     ansible.verbose        = false
#   end

#   config.vm.define "router" do |router|
# 	router.vm.hostname = "router.nctu.cs"
# 	router.vm.box = "vyos/current"
# 	router.vm.network :private_network, ip: "10.113.0.1"
# 	router.vm.network :forwarded_port, guest: 22, host: 2221, id: "ssh"
# end

  config.vm.define "ldapmaster" do |ldapm|
		# ldapm.vm.hostname = "ldapmaster.nctu.cs"
		# ldapm.vm.hostname = "ldapprovider.1.nasa"
		ldapm.vm.hostname = "ldap.1.nasa"
		ldapm.vm.network :private_network, ip: "10.113.0.2"
		ldapm.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh"
		ldapm.vm.network :forwarded_port, guest: 389, host: 389
	end

#   config.vm.define "ldapslave" do |ldaps|
# 		# ldaps.vm.hostname = "ldapslave.nctu.cs"
# 		ldaps.vm.hostname = "ldapconsumer.1.nasa"
# 		ldaps.vm.network :private_network, ip: "10.113.0.3"
# 		ldaps.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh"
# 	end

#   config.vm.define "ldapproxy1" do |ldapp1|
# 		ldapp1.vm.hostname = "ldapproxy1.nctu.cs"
# 		ldapp1.vm.network :private_network, ip: "10.113.0.4"
# 		ldapp1.vm.network :forwarded_port, guest: 22, host: 2224, id: "ssh"
# 	end

#   config.vm.define "ldapproxy2" do |ldapp2|
# 		ldapp2.vm.hostname = "ldapproxy2.nctu.cs"
# 		ldapp2.vm.network :private_network, ip: "10.113.0.5"
# 		ldapp2.vm.network :forwarded_port, guest: 22, host: 2225, id: "ssh"
# 	end

  config.vm.define "ldapclient" do |ldapc|
		# ldapc.vm.hostname = "ldapclient.nctu.cs"
		ldapc.vm.hostname = "workstation.1.nasa"
		ldapc.vm.network :private_network, ip: "10.113.0.6"
		ldapc.vm.network :forwarded_port, guest: 22, host: 2226, id: "ssh"
		ldapc.vm.provider "virtualbox" do |vc|
			vc.gui = false
			vc.memory = "250"
			vc.cpus   = "1"
			vc.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
		  end
	end

end

