stu_id: "4"

openssl_remote_ca_cert_dir: "/etc/openldap"
openldap_mdb_suffix: "dc={{ stu_id }},dc=nasa"
openldap_client_connect_uri: "ldap://ldapprovider.{{ stu_id }}.nasa/"
ldap_default_bind_dn: "cn=admin,{{ openldap_mdb_suffix }}"
ldap_default_authtok: MYPASSWD